### ISSUE TITLE
Add favicon, .webmanifest, OG and meta-tags to new site

### ISSUE THREAD

**Issue by a-chabin** [browserslist/browserl.ist#290]
## Favicon
- [x] Configure [with 2022 recommendations](https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs) 
     - [x] Put svg icon to `/client/assets`
     - [ ] ~~Add [Vite favicon plugin](https://www.npmjs.com/package/vite-plugin-favicon)~~
- [x] Create webmanifest

## SEO, Social
- [x] Open-graph description
- [x] Open-graph image — 1200x630px
- [x] Meta-tag description

Validation
- https://realfavicongenerator.net/
- Lighthouse in Chrome (PWA)
- https://www.opengraph.xyz

**Comment by ai** [comment]
I found favicon plugins not very useful. The guidance is very easy to do manually once. It is faster than dealing with plugin config.

Adding plugin for this one-time task will only increase `node_modules` and slow down build time.
